# Generated by Django 5.1.4 on 2025-03-13 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonological_awareness', models.FloatField()),
                ('vocabulary_understanding', models.FloatField()),
                ('sentence_comprehension', models.FloatField()),
                ('logical_reasoning', models.FloatField()),
                ('reading_comprehension', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='NumeracyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sense', models.FloatField()),
                ('basic_arithmetic', models.FloatField()),
                ('number_sequencing', models.FloatField()),
                ('spatial_awareness', models.FloatField()),
                ('memory_math', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
