# Generated by Django 5.1.4 on 2025-03-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_literacyscores_numeracyscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='handwriting_samples/%Y%m%d/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('paragraph_text', models.TextField(default='The little brown dog ran across the garden...')),
            ],
            options={
                'get_latest_by': 'submission_date',
            },
        ),
    ]
